version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: imagelite_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=imagelite
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - imagelite

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
        - imagelite

  sbootapp:
    build:
      dockerfile: Dockerfile
    container_name: imagelite_sbootapp
    restart: on-failure
    depends_on:
      - postgres
    ports:
       - "8080:8080"
    networks:
        - imagelite
    environment:
      POSTGRES_HOST: postgres


volumes:
  postgres_data:

networks:
    imagelite:
        driver: bridge