spring:
  application:
    name: imgeliteapi
  datasource:
    url: jdbc:postgresql://localhost:5432/imagelite
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB